# Configuration for probot-stale - https://github.com/probot/stale

# Around two Sprints TAT -- Arbitrary value
daysUntilStale: 0
daysUntilClose: 1

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - migration 🎫
  - security 🔓
  - vulnerability 🔓
  - dependencies

# Ignore issues in a milestone
exemptMilestones: true

# Label to use when marking as stale
staleLabel: stale 🍞

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.