# Note: pool property must be at least equal to sidekiq's concurrency setting:
# see "concurrency" attribute in sidekiq.yml
#
# https://github.com/mperham/sidekiq/wiki/Advanced-Options#concurrency

default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV['DB_POOL'] || 25 %>
  reaping_frequency: <%= ENV['DB_REAP_FREQ'] || 10 %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: colonesapp_development

test:
  <<: *default
  database: colonesapp_test

production:
  <<: *default
